### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by cdglasz**

### CODE REVIEW

**Comment by keromonkey1** [comment]
Hey Kyle, do you have Skype? 


     On Tuesday, March 17, 2015 9:09 PM, Christopher David Glasz <notifications@github.com> wrote:
   

 Merged #7.—

**Comment by kmackenzieii** [comment]
I don't have Skype.  Something you want to ask?

**Comment by keromonkey1** [comment]
I'm trying to find an efficient way for us all to communicate as a group besides email. I want to ask for updates and see if there's a way I can help on the proj 


     On Wednesday, March 18, 2015 4:10 PM, kmackenzieii <notifications@github.com> wrote:
   

 I don't have Skype. Something you want to ask?

**Comment by cdglasz** [comment]
Kaighen, can you write some method that will print out the map in a more readable format? Like the same format that you and I had in our AStar implementations?

**Comment by keromonkey1** [comment]
You mean the thing that prints the rows and columns in a series of 0s? 
like000000000000X00? 


     On Wednesday, March 18, 2015 4:24 PM, Christopher David Glasz <notifications@github.com> wrote:
   

 
Kaighen, can you write some method that will print out the map in a more readable format? Like the same format that you and I had in our AStar implementations?

**Comment by cdglasz** [comment]
Yeah
Any characters, as long as you can see the currently known layout of the room

**Comment by kmackenzieii** [comment]
We could use a more sophisticated way of deciding where to explore next.
Right now we just go to the farthest unexplored location.

**Comment by cdglasz** [comment]
I was thinking that heading to the nearest unexplored location would be better. Sure, with the farthest, you're *probably* going to be exploring more of the map along the way, but once you get the the destination, it's likely that you'll just turn around and go right back the way you came to the unexplored cells on the other side of the frontier. With shortest, or possibly some middling method to keep from just choosing adjacent cells, it's guaranteed that it'll fill out the area it's in before it searches new areas, which will save a lot of time

**Comment by keromonkey1** [comment]
I would recommend shortest/nearest searching also. 

And below is the base code that prints out the map and the Quagent's current location.If you'd like me to adjust it, I'd need to know the inputs and/or how they differ from the node indexes or the x/y locations
(again, I'd recommend skype or Facebook or something. Kyle, I know you have neither but we have both and Skype really is a useful tool. 
My team is using it for our group in our software engineering class also)
+++++++++++++++++++++++++++++++++++++++++++++++++++
/*Note the printLoc() and printMap() are not intended to be used together. Each of them prints out the map using different means*/



//draw the map (uses node indices)
        public void printLoc()
        {    
            int currentXindex=(int)(myX/32);
            int currentYindex=(int)(myY/32);
            System.out.println("\n\nScrag is at: "+currentXindex+" & "+currentYindex); 
            //printLoc(currentXindex,currentYindex); //feeds it the node index
        
        
            Node Johnny=matrix.get(0).get(0); 
            
            for(int sq=0;sq<matrix.size()*16;sq++)
            {
                    if(Johnny.row!=currentYindex || Johnny.col!=currentXindex) //print x in other locations
                        System.out.print("x"+" ");
                    else
                        System.out.print("0"+" "); //print zero at Scrag's current pos
                    
                    if(Johnny.getR()!=null)           //go through nodes, matching X pos first
                        Johnny=Johnny.getR(); 
                    else
                    {
                        while(Johnny.getL()!=null)    //backtrack...
                            Johnny=Johnny.getL(); 
                        Johnny=Johnny.getB();        //then go down a level and try again.
                        System.out.print("\n");
                    }
            }
        }
        
        
        //draws the map (uses x and y values)
        //this is larger because it is heavily comment-filled
        public void printMap()
        {
            int sq=0;
            Node Johnny=matrix.get(0).get(0); 
            boolean foundOne=false, foundBoth=false;
            
            
            /*get right node until space is found that has a lower X val
            than Scrag's current x val.
            if none is found, then scrag is in the furthest right square
            then...
            if it stops searching, it either means 
            A) there are no more squares left to search
            thus Scrag is at the bottom/top/end of grid, or
            B) the next square has a higher Y val then 
            Scrag's current position, thus Scrag must be in 
            current square. */
            
            //this finds the grad square Scrag is in based on x and y values
            //rather than node indices
            while(sq<matrix.size()*16 && foundBoth==false)
            {        //Note: 'Johnny' is a gridSquare
                    if(Johnny.getR()!=null && Johnny.getR().x <= myX)
                        Johnny=Johnny.getR(); 
                    else
                    {
                        if(Johnny.getB()!=null && Johnny.getB().y <= myY)
                            Johnny=Johnny.getB(); 
                        else
                            foundBoth=true;
                    }
                    sq++;
            }

            //right now, Johnny is already set to the node that Scrag is currently in.
            System.out.println("\n\nScrag is at: "+myX+" & "+myY+", and mapLoc is: "+Johnny.x+"/"+Johnny.y);
            Node Mike=matrix.get(0).get(0); 
            
            for(int sx=0;sx<matrix.size()*16;sx++)
            {
                    if(Mike.x!=Johnny.x || Mike.y!=Johnny.y) //print x in other locations
                        System.out.print("x"+" ");
                    else
                        System.out.print("0"+" "); //print zero at Scrag's current pos
                    if(Mike.getR()!=null)           //go through nodes, matching X pos first
                        Mike=Mike.getR(); 
                    else
                    {
                        while(Mike.getL()!=null)    //backtrack...
                            Mike=Mike.getL(); 
                        Mike=Mike.getB();        //then go down a level and try again.
                        System.out.print("\n");
                    }
            }
        }
         



     On Wednesday, March 18, 2015 11:56 PM, Christopher David Glasz <notifications@github.com> wrote:
   

 I was thinking that heading to the nearest unexplored location would be better. Sure, with the farthest, you're *probably* going to be exploring more of the map along the way, but once you get the the destination, it's likely that you'll just turn around and go right back the way you came to the unexplored cells on the other side of the frontier. With shortest, or possibly some middling method to keep from just choosing adjacent cells, it's guaranteed that it'll fill out the area it's in before it searches new areas, which will save a lot of time

**Comment by cdglasz** [comment]
That isn't going to work for this implementation. We're using a graph of vertices and edges, not a matrix, otherwise printing it nicey neat would be super simple. 
Take a look at the code on github. Create a fork off of master (don't edit master directly). You'll want to make a method in the Graph class that can print the way we want. You can make as many accessor methods as you need, but try not to change anything else in the class, in case it breaks something somewhere else in the program
When you have something that works and is commented, make a pull request into master, and Kyle will merge it

**Comment by cdglasz** [comment]
So can you guys take a look at the map building mechanics? Doesn’t seem like wall cells are being added according to the printed map. I can’t see what the issue is, try to see if you can find where it’s going wrong, whether it be in the addling thing or the map printing method

**Comment by kmackenzieii** [comment]
I've got the map building worked out. Just trying to sort out a couple
things before I upload.

**Comment by cdglasz** [comment]
Can you explain the reasoning behind why the path is being computed/traversed in the case where rays are being returned? Wouldn’t it make more sense to be doing that in the stopped events block?

**Comment by cdglasz** [comment]
Like I believe that there's a reason for it, because I tried moving it to where I think would make more sense, and it stopped working. I just don't know what the reason is.

**Comment by kmackenzieii** [comment]
Because you use the rays to determine where to go. By moving it to the
stopped area you make it so that he never makes a decision where to go in
the first place so there never is a stopped event in which to process the
next location.

**Comment by cdglasz** [comment]
I only mean in the searching state though, not the initial one. In the searching state, I would think that we would want to be popping waypoints off the path and moving to them only when we reach the previous waypoint on the path, i.e. when we get an event notifying that we've finished walking. Right now, it does an okay job of mapping a good portion of the room, but it doesn't seem like it's following the paths it calculates properly, because it will turn in circles or backtrack every so often, which A* would never produce if it's trying to reach the farthest unexplored point

**Comment by kmackenzieii** [comment]
I think that's mostly because the quagent does not move exactly how far you
tell it. I also put in a bit where if it gets stuck it will turn around and
walk a bit before continuing. I'm using the soldier on mine BTW.  Parasite
goes too far at once.

**Comment by cdglasz** [comment]
Yeah, I saw that, that seems like it works well. But I'm talking about in like the middle of a room. I don't know, I'll try messing with the structure and if I get something that seems to work more smoothly I'll open a pull request and you can take a look at it

**Pull request merged**
